version: '3.8'

services:
  pg:
    image: bitnami/postgresql:13.16.0
    container_name: pocket-js-server  # Nome do container
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=inorbit
